# Site settings
title: Consilium Inquaesitum
emails: [ aidan@caerdroia.org ]
description: > # this means to ignore newlines until "baseurl:"
    A slow descent into madness.
url: "http://caerdroia.org" # the base hostname & protocol for your site
twitter_usernames: [ AidanMedcalf, WhateverEmilyWants ]
github_usernames:  [ AidanMedcalf ]

# Build settings
markdown: kramdown
